version: "3"
services:
    web:
        container_name: red_string_web
        build:
            context: ./client
            dockerfile: Dockerfile
        image: vicki/red_string_web
        ports:
            - "3000:3000"
        volumes:
            - ./client:/app
    backend:
        container_name: red_string_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: vicki/red_string_server
        ports:
            - "5000:5000"
        volumes:
            - ./server:/app
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
